// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeAssignmentSystem.Core.Data;

#nullable disable

namespace SafeAssignmentSystem.DataBase.Migrations
{
    [DbContext(typeof(SafeAssignmentDbContext))]
    [Migration("20230622194547_SeedBaseFactoryAndWorkingShift")]
    partial class SeedBaseFactoryAndWorkingShift
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.DatabaseModels.Account.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Собствено име на потребител");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Фамилно име на потребител");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserWorkNumber")
                        .HasColumnType("int")
                        .HasComment("Табелен номер на потребителя");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasComment("Модел на потребителите");
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.DatabaseModels.Account.ApplicationUserPlantInstalation", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Id на потребител");

                    b.Property<Guid>("InstalationId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id на инсталация");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasComment("Поле указващо дали записът е изтрит");

                    b.HasKey("UserId", "InstalationId");

                    b.HasIndex("InstalationId");

                    b.ToTable("ApplicationUserPlantInstalations");

                    b.HasComment("Свързваща таблица между потребителите и инсталациите");
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.DatabaseModels.FactoryModels.PlantInstalation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Идентификационен ключ");

                    b.Property<Guid>("ComplexId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id на комплекс");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Пълно наименование на инсталацията");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Съкратено наименование на инсталацията");

                    b.HasKey("Id");

                    b.HasIndex("ComplexId");

                    b.ToTable("PlantInstalations");

                    b.HasComment("Модел на инсталациите");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4dabf64e-adb1-486a-b208-b07c5fabc440"),
                            ComplexId = new Guid("d90ccba2-389c-4a1a-ac97-5c54340dadd4"),
                            FullName = "Водородна",
                            Name = "ВИ"
                        },
                        new
                        {
                            Id = new Guid("8b6563b0-5bc0-4778-bc4c-30fa347d9854"),
                            ComplexId = new Guid("fe306aa1-f678-4e94-9d86-308ed58fd305"),
                            FullName = "Втечнени газове, авто и жп. наливни естакади",
                            Name = "ВГ и АЖПН"
                        },
                        new
                        {
                            Id = new Guid("13d901bf-8203-4280-ae70-24eef3fed196"),
                            ComplexId = new Guid("d90ccba2-389c-4a1a-ac97-5c54340dadd4"),
                            FullName = "Газова сяра",
                            Name = "ГС"
                        },
                        new
                        {
                            Id = new Guid("439d96e7-35fd-4037-a88e-ac56dd11e9d8"),
                            ComplexId = new Guid("bd922bb0-94af-4bf0-9a99-2431661a27b6"),
                            FullName = "Гранулация на полипропилен",
                            Name = "ГППр"
                        },
                        new
                        {
                            Id = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            ComplexId = new Guid("d90ccba2-389c-4a1a-ac97-5c54340dadd4"),
                            FullName = "Каталитичен крекинг",
                            Name = "ККр"
                        },
                        new
                        {
                            Id = new Guid("c7d3bad4-cd8c-4a73-a98c-3e57fc04b09d"),
                            ComplexId = new Guid("79afcb01-d8f3-4fe0-9fa2-fd95b72c615f"),
                            FullName = "Каталитичен реформинг",
                            Name = "КР"
                        },
                        new
                        {
                            Id = new Guid("0d5fc355-ba0d-494e-aa2d-421616e9f651"),
                            ComplexId = new Guid("79afcb01-d8f3-4fe0-9fa2-fd95b72c615f"),
                            FullName = "МТБЕ и хидроочистка-1 и 3",
                            Name = "МТБЕ и ХО 1, 3"
                        },
                        new
                        {
                            Id = new Guid("c639c036-bdc1-4e54-9425-c77ab00658a3"),
                            ComplexId = new Guid("125b8f04-7c38-4d1b-b39e-6d750e7bd037"),
                            FullName = "Очистни съоръжения",
                            Name = "ЦПС"
                        },
                        new
                        {
                            Id = new Guid("38a9c7f5-45b6-4783-a1ba-365f22cb8cea"),
                            ComplexId = new Guid("bd922bb0-94af-4bf0-9a99-2431661a27b6"),
                            FullName = "Полимеризация на пропилен",
                            Name = "ПП"
                        },
                        new
                        {
                            Id = new Guid("5078a11e-d2b0-40ca-ae46-79d81197af11"),
                            ComplexId = new Guid("d90ccba2-389c-4a1a-ac97-5c54340dadd4"),
                            FullName = "Регенерация на МДЕА и кисели води",
                            Name = "РМДЕА и РКВ"
                        },
                        new
                        {
                            Id = new Guid("7e9d0982-c5fa-493d-b8b1-30babddbdfcc"),
                            ComplexId = new Guid("d90ccba2-389c-4a1a-ac97-5c54340dadd4"),
                            FullName = "Регенерация на хексан",
                            Name = "РХ"
                        },
                        new
                        {
                            Id = new Guid("27e67a5e-9def-417e-b479-a3374ac01357"),
                            ComplexId = new Guid("d90ccba2-389c-4a1a-ac97-5c54340dadd4"),
                            FullName = "Сярно-кисело алкилиране и абсорбционно газофракциони",
                            Name = "СКА"
                        },
                        new
                        {
                            Id = new Guid("e9e9f60a-057a-4105-8adb-b0f4f0fbfcc5"),
                            ComplexId = new Guid("125b8f04-7c38-4d1b-b39e-6d750e7bd037"),
                            FullName = "ТЕЦ и топлопренос",
                            Name = "ТЕЦ"
                        },
                        new
                        {
                            Id = new Guid("0c3d7329-a0af-45ee-8ba2-4ac6b0320e3e"),
                            ComplexId = new Guid("d90ccba2-389c-4a1a-ac97-5c54340dadd4"),
                            FullName = "Хидрокрекинг на гудрон",
                            Name = "ХККр"
                        },
                        new
                        {
                            Id = new Guid("35dbc6f8-e63e-46a5-98ec-305161eca10f"),
                            ComplexId = new Guid("79afcb01-d8f3-4fe0-9fa2-fd95b72c615f"),
                            FullName = "Хидрообезсерване на бензин-1 и Хидроочистка-2",
                            Name = "ХО 2"
                        },
                        new
                        {
                            Id = new Guid("50465de6-39bd-4370-9e51-b7f60f56130a"),
                            ComplexId = new Guid("79afcb01-d8f3-4fe0-9fa2-fd95b72c615f"),
                            FullName = "Хидроочистка-5",
                            Name = "ХО 5"
                        },
                        new
                        {
                            Id = new Guid("e90898e2-831b-4266-8d4c-014cffefcf56"),
                            ComplexId = new Guid("125b8f04-7c38-4d1b-b39e-6d750e7bd037"),
                            FullName = "Химично обезсоляване на води и оборотно водоснабдяване",
                            Name = "ХВО"
                        },
                        new
                        {
                            Id = new Guid("c05340da-e358-47f7-822e-bde8030f456a"),
                            ComplexId = new Guid("79afcb01-d8f3-4fe0-9fa2-fd95b72c615f"),
                            FullName = "Централно газофракциониране и хидрообезсерване",
                            Name = "ЦГФИ"
                        },
                        new
                        {
                            Id = new Guid("1b3e962a-ab8f-4fec-87d3-3221edb3bad0"),
                            ComplexId = new Guid("d90ccba2-389c-4a1a-ac97-5c54340dadd4"),
                            FullName = "Производство на битуми и резервоарен парк за тъмни горива",
                            Name = "БИ"
                        });
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.DatabaseModels.FactoryModels.ProductionComplex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Идентификационен ключ");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Пълно наименование на комплекса");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Указател, показващ дали модела на комплекса е изтрит");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Съкратено наименование на комплекса");

                    b.HasKey("Id");

                    b.ToTable("ProductionComplexes");

                    b.HasComment("Модел на производствените комплекси");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d90ccba2-389c-4a1a-ac97-5c54340dadd4"),
                            FullName = "Дълбочинна преработка на нефт",
                            IsDeleted = false,
                            Name = "ДПН"
                        },
                        new
                        {
                            Id = new Guid("125b8f04-7c38-4d1b-b39e-6d750e7bd037"),
                            FullName = "Енергиен",
                            IsDeleted = false,
                            Name = "Eн"
                        },
                        new
                        {
                            Id = new Guid("bd922bb0-94af-4bf0-9a99-2431661a27b6"),
                            FullName = "Полипропилен",
                            IsDeleted = false,
                            Name = "ППр"
                        },
                        new
                        {
                            Id = new Guid("79afcb01-d8f3-4fe0-9fa2-fd95b72c615f"),
                            FullName = "Първична преработка на нефт",
                            IsDeleted = false,
                            Name = "ППН"
                        },
                        new
                        {
                            Id = new Guid("fe306aa1-f678-4e94-9d86-308ed58fd305"),
                            FullName = "Транспорт и съхранение на нефтопродукти и Пристанищен Терминал",
                            IsDeleted = false,
                            Name = "ТСНП и ПТ"
                        });
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.DatabaseModels.SafeAssignmentDocumentModels.SafeAssignmentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Идентификационен ключ");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2")
                        .HasComment("Дата и час на закриване на наряда");

                    b.Property<string>("ElectricianAppliedVoltageId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Id на потребител подал напрежение");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasComment("Състояние на наряда");

                    b.Property<bool>("IsAppliedVoltage")
                        .HasColumnType("bit")
                        .HasComment("Състояние на технологичната позиция");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Номер на наряд според вътрешнонарядната номерация");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("datetime2")
                        .HasComment("Дата и час на откриване на наряда");

                    b.Property<string>("PersonRequestedOpeningOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Id на потребител, поискал откриване на наряда");

                    b.Property<string>("PersonRequestedVoltageSupplyId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Id на потребител поискал подаване на напрежение");

                    b.Property<Guid>("TechnologicalPositionId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id на технологична позиция");

                    b.Property<string>("ЕlectricianClosingOrderId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Id на потребител закрил наряда");

                    b.Property<string>("ЕlectricianOpeningOrderId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Id на потребител открил наряда");

                    b.HasKey("Id");

                    b.HasIndex("ElectricianAppliedVoltageId");

                    b.HasIndex("PersonRequestedOpeningOrderId");

                    b.HasIndex("PersonRequestedVoltageSupplyId");

                    b.HasIndex("TechnologicalPositionId");

                    b.HasIndex("ЕlectricianClosingOrderId");

                    b.HasIndex("ЕlectricianOpeningOrderId");

                    b.ToTable("SafeAssignmentDocuments");

                    b.HasComment("Модел на нарядите");
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.DatabaseModels.StaffsModels.ChangedSchedule", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Дата");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Id на потребител който е на смяна(оператор или дежурен електромонтьор)");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id на смяна");

                    b.HasKey("Date", "ApplicationUserId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ChangedsSchedules");

                    b.HasComment("Модел на сменния график");
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.DatabaseModels.StaffsModels.WorkingShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Идентификационен ключ");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasComment("Краен час на смяната");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Име на смяната");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasComment("Начален час на смяната");

                    b.HasKey("Id");

                    b.ToTable("WorkingShifts");

                    b.HasComment("Модел на смените");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8dd62cbc-0f4d-4868-bdaa-0bb3980fc47d"),
                            EndTime = new DateTime(1, 1, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftName = "Р",
                            StartTime = new DateTime(1, 1, 1, 7, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("51e3023b-5967-4221-ba1e-977fdff10eda"),
                            EndTime = new DateTime(1, 1, 1, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftName = "1",
                            StartTime = new DateTime(1, 1, 1, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ad095ab8-ed2b-4f15-9f2d-088188db4ee2"),
                            EndTime = new DateTime(1, 1, 2, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftName = "2",
                            StartTime = new DateTime(1, 1, 1, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.FactoryModels.TechnologicalPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Идентификационен ключ");

                    b.Property<Guid>("InstalationId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Id на инсталация");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Наименование на технологичната позиция");

                    b.HasKey("Id");

                    b.HasIndex("InstalationId");

                    b.ToTable("TechnologicalPositions");

                    b.HasComment("Модел на технологична позиция");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c5e037a-4ad6-4ada-a3c8-bf8aa34b90ee"),
                            InstalationId = new Guid("13d901bf-8203-4280-ae70-24eef3fed196"),
                            Name = "MJ 401 A"
                        },
                        new
                        {
                            Id = new Guid("0da0c03c-eb4a-44dd-bb47-2438d7cd128b"),
                            InstalationId = new Guid("13d901bf-8203-4280-ae70-24eef3fed196"),
                            Name = "MJ 401 B"
                        },
                        new
                        {
                            Id = new Guid("3e61213e-5e51-4848-a916-51d45fb55dd9"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "B5"
                        },
                        new
                        {
                            Id = new Guid("e4914783-4d0f-4afa-b34e-9cbbf7953558"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "Н102-2"
                        },
                        new
                        {
                            Id = new Guid("ab117d29-20b6-400a-9747-0f8d1b8d098f"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "Н102-P"
                        },
                        new
                        {
                            Id = new Guid("936edbb9-9444-44cd-89f3-80fb27d70e9a"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "ЦК 201-1"
                        },
                        new
                        {
                            Id = new Guid("15d1308a-2e55-467c-b251-ee4b38262723"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "В 403"
                        },
                        new
                        {
                            Id = new Guid("7fcd955b-a234-4f5e-bb1d-68afd2374038"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "ЦК 201-2"
                        },
                        new
                        {
                            Id = new Guid("f48f6af8-4aa4-423f-b24f-9fbdfc4b0b39"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "Н102-1"
                        },
                        new
                        {
                            Id = new Guid("465a93ad-50e3-4b59-991a-1b9d1c04cf4e"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "В7"
                        },
                        new
                        {
                            Id = new Guid("1a452cb1-b1d1-4b48-9159-badcc40ba590"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "В6"
                        },
                        new
                        {
                            Id = new Guid("2c107550-7b23-4478-af9b-448d50d65a23"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "В102"
                        },
                        new
                        {
                            Id = new Guid("cd394570-be68-4b7f-8ee3-d9dc13caaf60"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "ЦП1"
                        },
                        new
                        {
                            Id = new Guid("6e7763d6-a561-4407-b95a-bcc0ec3ec42b"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "ЦП2"
                        },
                        new
                        {
                            Id = new Guid("6cc1db50-1604-4e5a-94de-cc3087cee06e"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "Н 210-3"
                        },
                        new
                        {
                            Id = new Guid("3a7e4c0e-6b25-4707-874d-953d619e7d93"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "Н 109"
                        },
                        new
                        {
                            Id = new Guid("1b1b7597-8065-4b33-8b7e-eb4fae5d4603"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "ПК101Р"
                        },
                        new
                        {
                            Id = new Guid("0487b9c4-ceca-47d0-9ea5-4ef33d9262c2"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "Н 109-1"
                        },
                        new
                        {
                            Id = new Guid("d926a392-d513-45a2-ada8-fe5a05ece6eb"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "ЦК 301"
                        },
                        new
                        {
                            Id = new Guid("a77de888-4132-4f2c-b0f7-bb7ffac78bf0"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "ЦК 301 Р"
                        },
                        new
                        {
                            Id = new Guid("1272bde9-d132-4a76-8be1-da94f41100e6"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "Н 109-2"
                        },
                        new
                        {
                            Id = new Guid("9ed832f2-c9b9-4bcf-b05f-388fe35c794d"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "ПК101"
                        },
                        new
                        {
                            Id = new Guid("c36b152f-e0e7-47b6-8776-ca90537b3b59"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "Н 109-Р"
                        },
                        new
                        {
                            Id = new Guid("2b1bca55-1492-4688-a530-04f88917888b"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "ЦП 3"
                        },
                        new
                        {
                            Id = new Guid("ace79e04-4547-4161-8212-dda77d678a42"),
                            InstalationId = new Guid("973994a0-3ee2-4aba-b422-bc12be18040c"),
                            Name = "ЦП 4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SafeAssignmentSystem.DataBase.Data.DatabaseModels.Account.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SafeAssignmentSystem.DataBase.Data.DatabaseModels.Account.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeAssignmentSystem.DataBase.Data.DatabaseModels.Account.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SafeAssignmentSystem.DataBase.Data.DatabaseModels.Account.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.DatabaseModels.Account.ApplicationUserPlantInstalation", b =>
                {
                    b.HasOne("SafeAssignmentSystem.DataBase.Data.DatabaseModels.FactoryModels.PlantInstalation", "Instalation")
                        .WithMany("ApplicationUserPlantInstalations")
                        .HasForeignKey("InstalationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SafeAssignmentSystem.DataBase.Data.DatabaseModels.Account.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserPlantInstalations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Instalation");
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.DatabaseModels.FactoryModels.PlantInstalation", b =>
                {
                    b.HasOne("SafeAssignmentSystem.DataBase.Data.DatabaseModels.FactoryModels.ProductionComplex", "Complex")
                        .WithMany("PlantInstalations")
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complex");
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.DatabaseModels.SafeAssignmentDocumentModels.SafeAssignmentDocument", b =>
                {
                    b.HasOne("SafeAssignmentSystem.DataBase.Data.DatabaseModels.Account.ApplicationUser", "ElectricianAppliedVoltage")
                        .WithMany("ElectriciansAppliedsVoltage")
                        .HasForeignKey("ElectricianAppliedVoltageId");

                    b.HasOne("SafeAssignmentSystem.DataBase.Data.DatabaseModels.Account.ApplicationUser", "PersonRequestedOpeningOrder")
                        .WithMany("PersonsRequestedsOpeningOrders")
                        .HasForeignKey("PersonRequestedOpeningOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeAssignmentSystem.DataBase.Data.DatabaseModels.Account.ApplicationUser", "PersonRequestedVoltageSupply")
                        .WithMany("PersonsRequestedsVoltageSupply")
                        .HasForeignKey("PersonRequestedVoltageSupplyId");

                    b.HasOne("SafeAssignmentSystem.DataBase.Data.FactoryModels.TechnologicalPosition", "TechnologicalPosition")
                        .WithMany("SafeAssignmentDocuments")
                        .HasForeignKey("TechnologicalPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeAssignmentSystem.DataBase.Data.DatabaseModels.Account.ApplicationUser", "ЕlectricianClosingOrder")
                        .WithMany("ЕlectriciansClosingOrders")
                        .HasForeignKey("ЕlectricianClosingOrderId");

                    b.HasOne("SafeAssignmentSystem.DataBase.Data.DatabaseModels.Account.ApplicationUser", "ЕlectricianOpeningOrder")
                        .WithMany("ЕlectriciansOpeningOrders")
                        .HasForeignKey("ЕlectricianOpeningOrderId");

                    b.Navigation("ElectricianAppliedVoltage");

                    b.Navigation("PersonRequestedOpeningOrder");

                    b.Navigation("PersonRequestedVoltageSupply");

                    b.Navigation("TechnologicalPosition");

                    b.Navigation("ЕlectricianClosingOrder");

                    b.Navigation("ЕlectricianOpeningOrder");
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.DatabaseModels.StaffsModels.ChangedSchedule", b =>
                {
                    b.HasOne("SafeAssignmentSystem.DataBase.Data.DatabaseModels.Account.ApplicationUser", "ApplicationUser")
                        .WithMany("ChangedsSchedules")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeAssignmentSystem.DataBase.Data.DatabaseModels.StaffsModels.WorkingShift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.FactoryModels.TechnologicalPosition", b =>
                {
                    b.HasOne("SafeAssignmentSystem.DataBase.Data.DatabaseModels.FactoryModels.PlantInstalation", "Instalation")
                        .WithMany("TechnologicalPositions")
                        .HasForeignKey("InstalationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instalation");
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.DatabaseModels.Account.ApplicationUser", b =>
                {
                    b.Navigation("ApplicationUserPlantInstalations");

                    b.Navigation("ChangedsSchedules");

                    b.Navigation("ElectriciansAppliedsVoltage");

                    b.Navigation("PersonsRequestedsOpeningOrders");

                    b.Navigation("PersonsRequestedsVoltageSupply");

                    b.Navigation("ЕlectriciansClosingOrders");

                    b.Navigation("ЕlectriciansOpeningOrders");
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.DatabaseModels.FactoryModels.PlantInstalation", b =>
                {
                    b.Navigation("ApplicationUserPlantInstalations");

                    b.Navigation("TechnologicalPositions");
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.DatabaseModels.FactoryModels.ProductionComplex", b =>
                {
                    b.Navigation("PlantInstalations");
                });

            modelBuilder.Entity("SafeAssignmentSystem.DataBase.Data.FactoryModels.TechnologicalPosition", b =>
                {
                    b.Navigation("SafeAssignmentDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
